@startuml
actor Invité
actor Client

left to right direction

rectangle "Système de l'application" {


    (Créer un compte) -- Invité
    (Se connecter au compte client) -- Invité

    Client -- (Rejoindre un évènement)
    Client -- (Modifier photo de profil)
    Client -- (Consulter dernières commandes)
    Client -- (Se déconnecter)

    (Rejoindre un évènement) ..> (Se connecter au compte client) : include
    (Modifier photo de profil) ..> (Se connecter au compte client) : include
    (Consulter dernières commandes) ..> (Se connecter au compte client) : include
    (Se déconnecter) <.. (Se connecter au compte client) : extend

    (Rejoindre un évènement) <.. (Consulter produits) : extend
    (Consulter produits) <.. (Ajouter articles au panier) : extend
    (Ajouter articles au panier) <.. (Passer commande) : extend
    (Passer commande) ..> (Payer) : include

    note right of (Payer)
     Payer englobe le choix de moyen de payement etc. tout le processus de payement
    end note
    
}
@enduml

